name: LexicographicTree

on:
  push:
    branches: [test]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: "18"
          architecture: "x64"

      - name: Build the project
        run: javac src/tree/LetterNode.java src/tree/LexicographicTree.java

      - name: run
        run: java -cp src tree.LexicographicTree
